name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          #Print the metrics to terminal
          echo "Model Metrics"
          cat metrics.txt
          
          # Create a markdown document, push metrics in this doc
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          #Push images to markdown doc
          echo "## Data Vizualization"
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          # Deliver the markdown doc 
          echo "## Deliver report.md"
          cml-send-comment report.md
          
          
          
          
          
          
          
          
